static checking cleanup; shellcheck on scripts
git-svn-id: https://svn.bingwo.ca/repos/sg3_utils/trunk@1102 6180dd3e-e324-4e3e-922d-17de1ae2f315

diff --git a/scripts/scsi_logging_level b/scripts/scsi_logging_level
--- a/scripts/scsi_logging_level
+++ b/scripts/scsi_logging_level
@@ -152,13 +152,13 @@ check_cmdline()
         invalid_cmdline invalid parameter "$@"
     fi
 
-    if [ $GET = "1" -a $SET = "1" ]
+    if [ ${GET} = "1" ] && [ ${SET} = "1" ]
     then
         invalid_cmdline options \'-c\', \'-g\' and \'-s\' are mutual exclusive
-    elif [ $GET = "1" -a $CREATE = "1" ]
+    elif [ ${GET} = "1" ] && [ ${CREATE} = "1" ]
     then
         invalid_cmdline options \'-c\', \'-g\' and \'-s\' are mutual exclusive
-    elif [ $SET = "1" -a $CREATE = "1" ]
+    elif [ ${SET} = "1" ] && [ ${CREATE} = "1" ]
     then
         invalid_cmdline options \'-c\', \'-g\' and \'-s\' are mutual exclusive
     fi
@@ -186,8 +186,7 @@ get_logging_level()
 {
     echo "Current scsi logging level:"
 #   LEVEL=$(sysctl -n dev.scsi.logging_level)
-    LEVEL=$(cat /proc/sys/dev/scsi/logging_level)
-    if [ $? != 0 ]
+    if ! LEVEL=$(cat /proc/sys/dev/scsi/logging_level)
     then
         echo "$SCRIPTNAME: could not read scsi logging level" \
              "(kernel probably without SCSI_LOGGING support)"
@@ -197,7 +196,7 @@ get_logging_level()
 
 show_logging_level()
 {
-    echo "/proc/sys/dev/scsi/logging_level = $LEVEL"
+    echo "/proc/sys/dev/scsi/logging_level = ${LEVEL}"
 
     LOG_ERROR=$((LEVEL & 7)); LEVEL=$((LEVEL>>3))
     LOG_TIMEOUT=$((LEVEL & 7)); LEVEL=$((LEVEL>>3))
@@ -226,10 +225,9 @@ set_logging_level()
 {
     echo "New scsi logging level:"
 #   sysctl -q -w dev.scsi.logging_level=$LEVEL
-    echo $LEVEL > /proc/sys/dev/scsi/logging_level
-    if [ $? != 0 ]
+    if ! echo ${LEVEL} > /proc/sys/dev/scsi/logging_level
     then
-        echo "$SCRIPTNAME: could not write scsi logging level $LEVEL"
+        echo "$SCRIPTNAME: could not write scsi logging level ${LEVEL}"
         echo "  kernel does not have SCSI_LOGGING support or needs superuser"
         exit 1
     fi
@@ -255,11 +253,11 @@ then
     create_logging_level
     set_logging_level
     show_logging_level
-elif [ $GET = "1" ]
+elif [ ${GET} = "1" ]
 then
     get_logging_level
     show_logging_level
-elif [ $CREATE = "1" ]
+elif [ ${CREATE} = "1" ]
 then
     create_logging_level
     show_logging_level
diff --git a/scripts/scsi_satl b/scripts/scsi_satl
--- a/scripts/scsi_satl
+++ b/scripts/scsi_satl
@@ -63,10 +63,10 @@ while test ! -z "$opt" -a -z "${opt##-*}"; do
   opt=${opt#-}
   case "$opt" in
     h|-help) usage ; exit 1 ;;
-    L|-log) let log=$log+1 ;;
-    q|-quiet) let quiet=$quiet+1 ;;
+    L|-log) log=${log}+1 ;;
+    q|-quiet) quiet=${quiet}+1 ;;
     v|-verbose) verbose="-v" ;;
-    *) echo "Unknown option: -$opt " ; exit 1 ;;
+    *) echo "Unknown option: -${opt} " ; exit 1 ;;
   esac
   shift
   opt="$1"
@@ -82,53 +82,51 @@ for command in "sg_inq" "sg_vpd" "sg_vpd -p di" "sg_vpd -p ai" "sg_luns" \
                "sg_turs" "sg_requests -s" "sg_senddiag -t" "sg_modes -a" \
                "sg_sat_identify"
 do
-  if [ $quiet -eq 0 ]
-    then echo "$command" "$1"
+  if [ ${quiet} -eq 0 ] ; then
+    echo "${command}" "${1}"
   fi
 
-  if [ $log -eq 0 ]
-  then
-    if [ $verbose ]
-    then
-      $command $verbose "$1" > /dev/null
+  if [ ${log} -eq 0 ] ; then
+    if [ ${verbose} ] ; then
+      ${command} ${verbose} "$1" > /dev/null
     else
-      $command "$1" > /dev/null 2>> /dev/null
+      ${command} "${1}" > /dev/null 2>> /dev/null
     fi
   else
-    $command $verbose "$1" > /dev/null 2>> scsi_satl.err
+    ${command} ${verbose} "${1}" > /dev/null 2>> scsi_satl.err
   fi
   res=$?
-  case "$res" in
+  case "${res}" in
     0) ;;
-    1) echo "  syntax error" ; let syntax=$syntax+1 ;;
-    2) echo "  not ready" ; let not_ready=$not_ready+1 ;;
-    3) echo "  medium error" ; let medium=$medium+1 ;;
-    5) echo "  illegal request, general" ; let illeg_req=$illeg_req+1 ;;
-    6) echo "  unit attention" ; let unit_attention=$unit_attention+1 ;;
-    9) echo "  illegal request, invalid opcode" ; let inv_opcode=$inv_opcode+1 ;;
-    11) echo "  aborted command" ; let aborted_command=$aborted_command+1 ;;
-    15) echo "  file error with $1 " ; let file_err=$file_err+1 ;;
-    20) echo "  no sense" ; let other_err=$other_err+1 ;;
-    21) echo "  recovered error" ; let recovered=$recovered+1 ;;
-    33) echo "  timeout" ; let timeout=$timeout+1 ;;
-    97) echo "  response fails sanity" ; let sanity=$sanity+1 ;;
-    98) echo "  other SCSI error" ; let other_err=$other_err+1 ;;
-    99) echo "  other error" ; let other_err=$other_err+1 ;;
-    *) echo "  unknown exit status for sg_inq: $res" ; let other_err=$other_err+1 ;;
+    1) echo "  syntax error" ; syntax=${syntax}+1 ;;
+    2) echo "  not ready" ; not_ready=${not_ready}+1 ;;
+    3) echo "  medium error" ; medium=${medium}+1 ;;
+    5) echo "  illegal request, general" ; illeg_req=${illeg_req}+1 ;;
+    6) echo "  unit attention" ; unit_attention=${unit_attention}+1 ;;
+    9) echo "  illegal request, invalid opcode" ; inv_opcode=${inv_opcode}+1 ;;
+    11) echo "  aborted command" ; aborted_command=${aborted_command}+1 ;;
+    15) echo "  file error with $1 " ; file_err=${file_err}+1 ;;
+    20) echo "  no sense" ; other_err=${other_err}+1 ;;
+    21) echo "  recovered error" ; recovered=${recovered}+1 ;;
+    33) echo "  timeout" ; timeout=${timeout}+1 ;;
+    97) echo "  response fails sanity" ; sanity=${sanity}+1 ;;
+    98) echo "  other SCSI error" ; other_err=${other_err}+1 ;;
+    99) echo "  other error" ; other_err=${other_err}+1 ;;
+    *) echo "  unknown exit status for sg_inq: $res" ; other_err=${other_err}+1 ;;
   esac
 done
 
 echo ""
-let total_bad_err=$file_err+$inv_opcode+$illeg_req+$medium+$aborted_command
-let total_bad_err+=$other_err+$recovered+$sanity+$syntax+$timeout
+total_bad_err=$(( file_err+inv_opcode+illeg_req+medium ))
+total_bad_err+=$(( other_err+recovered+sanity+syntax ))
+total_bad_err+=$(( timeout+aborted_command ))
 
-let total_allow_err=$not_ready+$unit_attention
+total_allow_err=$(( not_ready+unit_attention ))
 
   echo "total number of bad errors: $total_bad_err "
 
-if [ $total_allow_err -gt 0 ]
-  then
-  echo "total number of allowable errors: $total_allow_err "
+if [ "${total_allow_err}" -gt 0 ] ; then
+  echo "total number of allowable errors: ${total_allow_err} "
 fi
 
-exit $total_bad_err
+exit ${total_bad_err}
